database:
  type: SQLITE

  mysql:
    host: localhost
    port: '3306'
    user: root
    password: ''
    database: minecraft

  redis:
    enabled: false
    host: localhost
    port: 6379
    password: '1234'